name: ci
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '6 6 * * 5'

jobs:
  build:
    concurrency:
      group: 'prd-deploy'
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-skip-session-tagging: true
          role-to-assume: "arn:aws:iam::341857463381:role/gha-blog"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: './fetch.sh'
      - run: 'npm ci'
      - run: 'npx next build'
      - run: 'rsync -r public/ out'
      - run: 'bundle exec ruby upload.rb out "prd/" "sorah-jp"'

